---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nifi-registry.fullname" . }}-adminconfig
  labels:
    {{- include "nifi-registry.labels" . | nindent 4 }}
data:
{{ (tpl (.Files.Glob "nifiAdminGenerated/*").AsConfig . ) | indent 2 }}
