---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nifi-registry.fullname" . }}-config
  labels:
    {{- include "nifi-registry.labels" . | nindent 4 }}
data:
{{ (tpl (.Files.Glob "configs/*").AsConfig . ) | indent 2 }}
