apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ca.fullname" . }}
  labels:
    {{- include "ca.labels" . | nindent 4 }}
type: Opaque
data:
  config.json: |-
    {{ .Files.Get "cacert/config.json" | b64enc }}
  nifi-ca-keystore.jks: |-
    {{ .Files.Get "cacert/nifi-ca-keystore.jks" | b64enc }}
